custombucket = "myintellipaatdb"
table = "intellipaat"
databasehost = "database-1.cxryvfqwnot1.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "Adroit123"
s3database = "myintellipaatdb"
kapp = "http://10.0.141.116:31018"
